spring:
  application:
    name: todoapp

  datasource:
    url: jdbc:mysql://lion-db.cpcckaaq6g4b.ap-northeast-2.rds.amazonaws.com/mydatabase
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect